### ISSUE TITLE
tagStandard41h12 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TON14** [pupil-labs/apriltags#19]
Detecting tagStandard41h12
AprilTag library compiled from source

```
at_detector = Detector(searchpath=['/usr/local/lib'],
                       families='tagStandard41h12',
                       nthreads=1,
                       quad_decimate=1.0,
                       quad_sigma=0.0,
                       refine_edges=1,
                       decode_sharpening=0.25,
                       debug=0)
```
Output
```
[]
Segmentation fault (core dumped)
```

When change nthreads=1 to nthreads=2
```
at_detector = Detector(searchpath=['/usr/local/lib'],
                       families='tagStandard41h12',
                       nthreads=2,
                       quad_decimate=1.0,
                       quad_sigma=0.0,
                       refine_edges=1,
                       decode_sharpening=0.25,
                       debug=0)
```

Output
```
[]

```
My image
![IMG_6263](https://user-images.githubusercontent.com/15056272/70692915-741aac80-1ccd-11ea-81a3-e3bbc4ce6211.jpg)

**Comment by pfaion** [comment]
Hi @TON14 
can you try removing the `searchpath` keyword from the `Detector()` initialization and see if it works?

This keyword is actually not needed anymore in the adjusted wrapper that we are providing. We are internally shipping the original apriltag libraries as part of the python package and thus know where the searchpath is.

**Comment by TON14** [comment]
@pfaion 
```
at_detector = Detector(families='tagStandard41h12',
                       nthreads=1,
                       quad_decimate=1.0,
                       quad_sigma=0.0,
                       refine_edges=1,
                       decode_sharpening=0.25,
                       debug=1
```)

Output
Debug images were created.
Now with nthreads=1  no error Segmentation fault (core dumped).
But 0 tag founded
`[ ]`

**Comment by TON14** [comment]
LOL =) i just print wrong tags

**Comment by pfaion** [comment]
@TON14 
Glad to hear this fixed the issue. The README is already updated on GitHub from #18 
Guess we'll have to push a new release to PyPI for updating the docs there as well 😞
