### ISSUE TITLE
circular tags detection error

### ISSUE THREAD

**Issue by walchko** [pupil-labs/apriltags#32]
This doesn't seem to detect circular apriltags:

```python
import cv2
from pupil_apriltags import Detector
import numpy as np

im = cv2.imread("pics/tag21_07_00020.png", cv2.IMREAD_UNCHANGED)
d = Detector(families='tagCircle21h7',
        nthreads=1,
        quad_decimate=1.0,
        quad_sigma=0.0,
        refine_edges=1,
        decode_sharpening=0.25,
        debug=1)

tags = d.detect(im, estimate_tag_pose=False, camera_params=None, tag_size=None)
print(f"{len(tags)} tags found") 

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-9-86793bd9058c> in <module>
----> 1 tags = d.detect(im, estimate_tag_pose=False, camera_params=None, tag_size=None)
      2 print(f"{len(tags)} tags found")

~/venv/lib/python3.8/site-packages/pupil_apriltags/bindings.py in detect(self, img, estimate_tag_pose, camera_params, tag_size)
    403 image of type numpy.uint8."""
    404 
--> 405         assert len(img.shape) == 2
    406         assert img.dtype == numpy.uint8
    407 

AssertionError: 
```

Here is the tag:

![tag21_07_00020](https://user-images.githubusercontent.com/918960/102724280-80701700-42dc-11eb-8d53-0fb94b169164.png)

What am I doing wrong?

**Comment by AlexVeuthey** [comment]
The error you get is because you do not have 2 dimensions in your image, but likely 3 due to reading the image as RGB. Try reading/converting to grayscale 1-channel and it should work.

**Comment by walchko** [comment]
So that doesn't work. I pulled a circular tag from Apriltags pre-rendered tags [here](https://github.com/AprilRobotics/apriltag-imgs/blob/master/tagCircle49h12/tag49_12_00000.png)

![tag49_12_00000](https://user-images.githubusercontent.com/918960/109370833-f7430680-786f-11eb-9438-d73706083fc9.png)

The image RGBA with the alpha layer giving the circular'ish aspect to the tag. 

```python
d = Detector(families='tagCircle49h12',
        nthreads=1,
        quad_decimate=1.0,
        quad_sigma=0.0,
        refine_edges=1,
        decode_sharpening=0.25,
        debug=1)

im = cv2.imread("pics/tag49_12_00000.png", cv2.IMREAD_UNCHANGED)
im = cv2.cvtColor(im, cv2.COLOR_BGRA2GRAY)

tags = d.detect(im, estimate_tag_pose=False, camera_params=None, tag_size=None)
print(f"{len(tags)} tags found")
```

Returns: `0 tags found`

I also tried reading it in as grayscale with `im = cv2.imread("pics/tag49_12_00000.png", 0)` and that didn't help.

Am I somehow setting up the detector wrong?

**Comment by AlexVeuthey** [comment]
Ah yes I didn't think about it, I had the same issue not long ago. If you use the tags as input, the resolution is extremely small and nothing will be detected.

Try upscaling the tag image to 150x150 or something in this range. Beware of resampling that might make edges blurry.

**Comment by walchko** [comment]
Thanks! Yes, that can be a problem ... I forgot about it too and fixated on the alpha layer as the issue since other tags didn't have an alpha layer.

You can easily scale without blurriness by using `cv2.INTER_AREA` or `cv2.INTER_NEAREST` since they appear to give nice crisp edges compared to other methods I have tried.

```python
def scale(im, s=1.0):
    (h,w) = im.shape
    return cv2.resize(im, (s*h, s*w,), interpolation=cv2.INTER_AREA)
```

![download](https://user-images.githubusercontent.com/918960/109393453-bab6ef80-78ef-11eb-8c18-2a67b09d9b02.png)
