### ISSUE TITLE
Failed building wheel for pupil-apriltags

### ISSUE THREAD

**Issue by pinhaocheng** [pupil-labs/apriltags#41]
Hello there,

[It seems like this repo is able to support apriltags on windows](https://pupil-labs.com/releases/core/v1.15/), however, I faced some difficulties when installing it on VS code (windows 10).

It seems like it's stuck at the building wheel step.

I am using the `pip install pupil-apriltags` method, with the latest `python 3.9.6` and `pip 21.2.3`.

Details:

```
Building wheel for pupil-apriltags (PEP 517) ... error

  Complete output (46 lines):
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  See also "C:/Users/user/AppData/Local/Temp/pip-req-build-9qtru2dv/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".       

  -- Trying "Visual Studio 15 2017 x64 v141" generator - failure

  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.9 requires Microsoft Visual Studio 2019.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  Or with "Visual Studio 2019":

    https://visualstudio.microsoft.com/vs/

  ERROR: Failed building wheel for pupil-apriltags
Failed to build pupil-apriltags
ERROR: Could not build wheels for pupil-apriltags which use PEP 517 and cannot be installed directly
```

Any help provided would be greatly appreciated!

**Comment by ejs94** [comment]
I've already had this problem, it was necessary to install Visual Studio in order to install the library.

>   Building windows wheels for Python 3.9 requires Microsoft Visual Studio 2019.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

> Or with "Visual Studio 2019":

    https://visualstudio.microsoft.com/vs/

**Comment by pinhaocheng** [comment]
@ejs94 

I already have Visual Studio 2019 installed. I found this [thread](docs.microsoft.com/en-us/answers/questions/365971/unable-to-install-visual-c-build-tools.html), and this [video](https://www.youtube.com/watch?v=p_R3tXSq0KI). I have followed what they did but I have no luck building the wheel still.

Did you do anything differently?  I might be missing something that I didn't notice.

**Comment by mark-belbin** [comment]
I had to downgrade to python 3.7 for this to work, had the same issues on 3.9!

**Comment by pinhaocheng** [comment]
Thanks @mark-belbin!

Downgraded to python 3.7.9 and it's working now.
